FROM ubuntu:23.04
COPY . . 
WORKDIR /data
RUN apt-get update
RUN apt-get install gcc -y
RUN apt-get install g++ -y
RUN apt-get install vim -y
RUN apt-get install net-tools -y
EXPOSE 5000                  
