services:
  python:
    build:
      context: python
    depends_on:
      - db
    volumes:
      - /Users/eleven/workspace:/data/workspace
    networks:                                                                       
      - "default"
    tty: true

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - default
    depends_on:
      - db
  
  # backend:
  #   build:
  #     context: backend
  #     target: development
  #   secrets:
  #     - db-password
  #   depends_on:
  #     - db
  #   networks:                                                                       
  #     - "default"  
  db:
    image: mariadb
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
    networks:                                                                       
      - "default"  

  # proxy:
  #   build: proxy
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - backend
  #   networks:                                                                       
  #     - "default"  
volumes:
  db-data:
  grafana-data:

secrets:
  db-password:
    file: db/password.txt
# 网络                                                                              
networks:                                                                           
  default:                                                                          
    driver: bridge                                                                  
    ipam:                                                                           
      config:                                                                       
        - subnet: 172.16.58.0/24                                                         

